#### *Help rendered by Microsoft Co-Pilot and Claude Sonnet 3.5 within VS Code*

In [1]:
#import Python packages first
import numpy as np
import pandas as pd

# Question 1
*Select all numeric columns except float from the DataFrame `dft`.*

## Answer 1

In [2]:
# Create a sample DataFrame
dft = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [1.0, 2.0, 3.0],
    'C': ['a', 'b', 'c']
})
dft

   A    B  C
0  1  1.0  a
1  2  2.0  b
2  3  3.0  c

In [3]:
dft.select_dtypes(include='number', exclude='float')

   A
0  1
1  2
2  3

In [4]:
numeric_columns = dft.select_dtypes(include='number', exclude='float')

In [5]:
numeric_columns

   A
0  1
1  2
2  3

# Question 2
*How do you return the last 3 rows of a DataFrame `df`?*

## Answer 2

In [6]:
# Create a DataFrame with 100 records
df = pd.DataFrame({
    'integers': np.arange(100),                    # 0 to 99
    'floats': np.random.uniform(0, 100, 100),     # random floats between 0 and 100
    'random_ints': np.random.randint(1, 1000, 100) # random integers between 1 and 1000
})
df

    integers     floats  random_ints
0          0  42.278721          346
1          1  42.580677          403
2          2  81.972190          221
3          3  60.091426          425
4          4  24.920540          550
..       ...        ...          ...
95        95  62.974922          893
96        96  93.997978          843
97        97   5.880908          325
98        98  10.632522          535
99        99  72.000197          304

[100 rows x 3 columns]

In [7]:
#return the last 3 rows of the DataFrame
df.tail(3)

    integers     floats  random_ints
97        97   5.880908          325
98        98  10.632522          535
99        99  72.000197          304

# Question 3
*Return the minimum and maximum of a Series x as a new Series with the index ["min", "max"].*

## Answer 3

In [8]:
# Create a sample Series
x = pd.Series([1, 3, 5, 7, 9, 2, 4, 6, 8, 10])
x

0     1
1     3
2     5
3     7
4     9
5     2
6     4
7     6
8     8
9    10
dtype: int64

In [9]:
# Create a new Series with min and max values
min_max = pd.Series([x.min(), x.max()], index=['min', 'max'])
min_max

min     1
max    10
dtype: int64

# Question 4
*Multiply df1 and df2 (two DataFrames) with a fill_value of 1.*

## Answer 4

In [10]:
# Create two sample DataFrames
df1 = pd.DataFrame({
       'A': [1,2,3,4],
       'B': [2,4,6,8]
})
df2 = pd.DataFrame({
    'A': [100, 200, 300],
    'B': [2,3,4]
})

In [11]:
df1

   A  B
0  1  2
1  2  4
2  3  6
3  4  8

In [12]:
df2

     A  B
0  100  2
1  200  3
2  300  4

In [13]:
df1, df2 #display both DataFrames together

(   A  B
 0  1  2
 1  2  4
 2  3  6
 3  4  8,
      A  B
 0  100  2
 1  200  3
 2  300  4)

In [14]:
# Multiply df1 and df2 with fill_value=1 and convert to integers    
result = df1.multiply(df2, fill_value=1).astype(int)
# OR result = df1.mul(df2, fill_value=1).astype(int)
result

     A   B
0  100   4
1  400  12
2  900  24
3    4   8

# Question 5
*How do you create a DataFrame from a nested dictionary of dictionaries?*

## Answer 5

In [15]:
# Create a nested dictionary of dictionaries
nested_dict = {
    'student1': {
        'name': 'John',
        'age': 20,
        'grades': {'math': 90, 'science': 95}
    },
    'student2': {
        'name': 'Emma',
        'age': 21,
        'grades': {'math': 88, 'science': 92}
    }
}

# Create DataFrame from nested dictionary
df = pd.DataFrame.from_dict(nested_dict, orient='index')
df

          name  age                       grades
student1  John   20  {'math': 90, 'science': 95}
student2  Emma   21  {'math': 88, 'science': 92}

In [16]:
# To access the nested 'grades' dictionary, we can use json_normalize
from pandas import json_normalize

# Normalize the grades column
grades_df = pd.json_normalize(df['grades'])
grades_df.index = df.index  # Keep the same index as the main DataFrame

# Now combine with the other columns
result = pd.concat([df[['name', 'age']], grades_df], axis=1)
result

          name  age  math  science
student1  John   20    90       95
student2  Emma   21    88       92

Notes from `Claude Sonnet`:

First cell is a markdown header for Answer 5

Second cell shows how to create a DataFrame from a nested dictionary:  
- Creates a nested dictionary with student information  
- Uses `pd.DataFrame.from_dict()` with `orient='index'` to create the DataFrame  
- The **outer** dictionary keys become the index  
- The **inner** dictionaries become the columns  

Third cell shows how to handle deeply nested dictionaries:  
- Uses `json_normalize` to flatten the nested 'grades' dictionary  
- Combines the flattened grades with the other columns  
- Shows how to preserve the index during the process  

When you run these cells, you'll see:  
- The initial DataFrame with the nested structure  
- The final DataFrame with all nested data flattened into columns  

This is particularly useful when working with JSON data or complex nested data structures that you want to analyze in a tabular format.